### ISSUE TITLE
1.20.5 and .6

### ISSUE THREAD

**Issue by cqm3ron** [Nettakrim/Fake-AFK#11]
Updates would be nice, and 1.21 when it releases in abt a week :D

**Comment by Nettakrim** [comment]
im going to go through all my mods and update them to both versions when i have the time next week

**Comment by cqm3ron** [comment]
Any ETA on this?

**Comment by Nettakrim** [comment]
i am currently going through my mods, however i got sidetracked adding features to one of them lol

**Comment by Nettakrim** [comment]
(fake afk is also lower on my priority list lol)

**Comment by Nettakrim** [comment]
https://modrinth.com/mod/fake-afk/version/1.0.5
